<a href="https://colab.research.google.com/github/mohtashim0007/Machine-Learning-Projects/blob/main/NumPyExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating arrays 


In [1]:
import numpy as np

In [2]:
arr = np.array([[2,5,1],[2,4,7]])
print(arr)

[[2 5 1]
 [2 4 7]]


Iteration over array like c

In [3]:
for row in arr:
  for el in row:
    print(el)

2
5
1
2
4
7


Iteration over array in terms of indexs

In [4]:
i,j = arr.shape
print(i,j)

2 3


In [5]:
for rowi in range(i):
  for rowj in range(j):
    print(arr[rowi][rowj])

2
5
1
2
4
7


Sum of numbers in coulumnwise and row wise


In [6]:
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[4 9 8]
[ 8 13]


Array with different datatypes


In [7]:
arr2 = np.array([[1,2,'str'],['sw',2,3]])
print(arr2)
print(type(arr2))
print(arr2.dtype)

[['1' '2' 'str']
 ['sw' '2' '3']]
<class 'numpy.ndarray'>
<U21


Arrange numbers using arrange and linspace

In [8]:
arr3 = np.arange(5,0,-2)
print(arr3)

[5 3 1]


In [9]:
arr4 = np.linspace(2,10,4, dtype=int)
print(arr4)

[ 2  4  7 10]


Initializing arrays with empty, ones and zeros

In [10]:
arr5 = np.empty([2,2])
arr6 = np.ones([2,5])
arr7 = np.zeros([3,5])

Initialize array as ones on diagonal

In [11]:
arr8 = np.eye(2,2)
print(arr8)

[[1. 0.]
 [0. 1.]]


Initialize array as identity


In [12]:
arr9 = np.identity(5)
print(arr9)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


copy and view

In [13]:
arr = np.arange(2,10)
print(arr)
arr2 = arr.copy()
print(id(arr2))
arr3 = arr.view()
print(id(arr3))
print(id(arr))

[2 3 4 5 6 7 8 9]
140155992239152
140156053797552
140155992239536


appending values 

In [14]:
arr1 = np.append(arr,[2,4])
print(arr1)
print(np.append(arr,arr1))

#2d append

arr = np.arange(10).reshape(2,5)
print(arr)
arr2 = np.arange(10,20).reshape(2,5)
print(arr2)

print(np.append(arr,arr2,axis=0))

[2 3 4 5 6 7 8 9 2 4]
[2 3 4 5 6 7 8 9 2 3 4 5 6 7 8 9 2 4]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [15]:
arr = np.linspace(1,7,4,dtype=int).reshape(2,2)
arr2 = np.linspace(10,17,4,dtype=int).reshape(2,2)
print(arr)
print(arr2)

[[1 3]
 [5 7]]
[[10 12]
 [14 17]]


In [16]:
print(np.dot(arr,arr2))

[[ 52  63]
 [148 179]]
