<a href="https://colab.research.google.com/github/mohtashim0007/Machine-Learning-Projects/blob/main/PreprocessingsWithScikitLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import preprocessing as pp
from sklearn import datasets
import pandas as pd
import numpy as np


In [ ]:
data = datasets.load_breast_cancer()
target = data.target
data = data.data
print(data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


#*Standardization*

In [ ]:
sc = pp.StandardScaler()
data_sc = sc.fit_transform(data)

#scaling MinMaxScaler

In [ ]:
mmsc = pp.MinMaxScaler()
data_mmsc = mmsc.fit_transform(data)
print(data_mmsc)

[[0.52103744 0.0226581  0.54598853 ... 0.91202749 0.59846245 0.41886396]
 [0.64314449 0.27257355 0.61578329 ... 0.63917526 0.23358959 0.22287813]
 [0.60149557 0.3902604  0.59574321 ... 0.83505155 0.40370589 0.21343303]
 ...
 [0.45525108 0.62123774 0.44578813 ... 0.48728522 0.12872068 0.1519087 ]
 [0.64456434 0.66351031 0.66553797 ... 0.91065292 0.49714173 0.45231536]
 [0.03686876 0.50152181 0.02853984 ... 0.         0.25744136 0.10068215]]


#Normalization


In [ ]:
iris = datasets.load_iris()
iris_normalized = pp.Normalizer()
iris_normalized = iris_normalized.fit_transform(iris.data)
print(iris_normalized.mean(axis=0))

[0.75140029 0.40517418 0.45478362 0.14107142]


In [ ]:
iris_target = iris.target
iris_target = iris_target.reshape(1,-1)
print(iris_target.shape)

(1, 150)


In [ ]:
ohe = pp.OneHotEncoder()
iris_target_ohe = ohe.fit_transform(iris_target)
print(iris_target_ohe.toarray())

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


In [ ]:
iris_data_nan = pd.DataFrame([iris.data[:50,:]])

ValueError: ignored

In [ ]:
 regions = ['HYD', 'CHN', 'MUM', 'HYD', 'KOL', 'CHN']
print(pp.LabelEncoder().fit(regions).transform(regions))

[1 0 3 1 2 0]


In [ ]:
 regions = ['HYD', 'CHN', 'MUM', 'HYD', 'KOL', 'CHN']
print(pp.OneHotEncoder().fit(regions).transform(regions))

ValueError: ignored